kind: Secret
apiVersion: v1
metadata:
  name: microservice-admin-console
  namespace: skillbox-alpha
data:
  CLOUDINARY_KEY: NDM5NTQyMzEyMjQzODI5
  CLOUDINARY_NAME: ZGEwd3I5eTUx
  CLOUDINARY_SECRET: RmtQRkdKRFhHWkFjM001SXFtSWJGQ1FMWFF3
  DB_HOST: cG9zdGdyZXMtc2VydmljZQ==
  DB_NAME: c2tpbGxib3g=
  DB_PASSWORD: YWRtaW4tY29uc29sZQ==
  DB_SCHEMA: YWRtaW4tY29uc29sZQ==
  DB_USERNAME: YWRtaW4tY29uc29sZQ==
type: Opaque



---




kind: Deployment
apiVersion: apps/v1
metadata:
  name: microservice-admin-console
  namespace: skillbox-alpha
  labels:
    app: microservice-admin-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-admin-console
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservice-admin-console
      annotations:
        kubectl.kubernetes.io/restartedAt: '2023-05-17T14:51:16+03:00'
    spec:
      volumes:
        - name: microservice-admin-console
          configMap:
            name: microservice-admin-console
            items:
              - key: application.yml
                path: application.yml
            defaultMode: 420
      containers:
        - name: app
          image: alphateam35/microservice-admin-console:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: '-Xms128m -Xmx256m -Xss512k'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: microservice-admin-console
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservice-admin-console
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-admin-console
                  key: DB_PASSWORD
          resources:
            limits:
              cpu: 300m
              memory: 450Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: microservice-admin-console
              mountPath: /app/config




---


kind: Service
apiVersion: v1
metadata:
  name: microservice-admin-console
  namespace: skillbox-alpha
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30288
  selector:
    app: microservice-admin-console
  type: NodePort

