apiVersion: v1
kind: Secret
metadata:
  name: microservice-dialog
  namespace: skillbox-alpha
stringData:
  DB_HOST: "postgres-service"
  DB_PASSWORD: "dialog"
  DB_SCHEMA: "dialog"
  DB_USERNAME: "dialog"
  DB_NAME: "skillbox"

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-dialog
  namespace: skillbox-alpha
data:
  application.yml: |-

    server:
      port: 8080

    spring:
      liquibase:
        enabled: true
        drop-first: false
        change-log: classpath:database-dialog-changelog.xml
        default_schema: dialog

      datasource:
        url: jdbc:postgresql://postgres-service:5432/skillbox
        username: dialog
        password: dialog
        driverClassName: org.postgresql.Driver

      jpa:
        show-sql: false
        hibernate:
          ddl-auto: none
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQL10Dialect
            format_sql: true
            default_schema: dialog
        open-in-view: false

    kafka:
      bootstrap-servers: kafka-statefulset-0.kafka-svc.kafka.svc.cluster.local:9092
      consumer:
        group-id: dialog.1
        concurrency: 3
        max.poll.interval.ms: 1000  
        spring.json.trusted.packages: ru.skillbox.diplom.group35.*
      producer:
        retries: 3
      topic:
        partition-count: 3
        replication-factor: 1
        reply: t.dialog.message.out
        request: t.dialog.message.in
        
    springdoc:
      api-docs:
        enabled: true
        path: '/api/v1/dialogs/v3/api-docs'
      swagger-ui:
        path: '/api/v1/dialogs/swagger-ui'
        doc-expansion: none
        disable-swagger-default-url: true

    logging:
      level:
        org.springframework: info
        org.apache.kafka.clients.producer: ERROR
        
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: microservice-dialog
  namespace: skillbox-alpha
  labels:
    app: microservice-dialog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-dialog
  template:
    metadata:
      labels:
        app: microservice-dialog
    spec:
      volumes:
        - name: microservice-dialog
          configMap:
            name: microservice-dialog
            items:
              - key: application.yml
                path: application.yml
      containers:
        - name: app
          image: alphateam35/microservice-dialog:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: JAVA_OPTIONS
              value: '-Xms128m -Xmx256m -Xss512k'
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: microservice-dialog
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: microservice-dialog
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-dialog
                  key: DB_PASSWORD
          resources:
            limits:
              cpu: 300m
              memory: 450Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: microservice-dialog
              mountPath: /app/config
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: microservice-dialog
  namespace: skillbox-alpha
spec:
  selector:
    app: microservice-dialog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort




