kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pg-db-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate



---




apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-db-pv
  namespace: skillbox-alpha
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pg-db-storage
  hostPath:
    path: /tmp/skillbox/postgres
    
    
    
---



apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pg-db-storage
  resources:
    requests:
      storage: 1Gi
      
      
      
---



kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgres-deployment
  namespace: skillbox-alpha
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
            claimName: pg-db-pvc
      containers:
        - name: postgres
          image: postgres:15.1
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_PASSWORD
              value: skillbox
            - name: POSTGRES_DB
              value: skillbox
            - name: POSTGRES_USER
              value: skillbox
          volumeMounts:
            - name: postgres-pv-claim
              mountPath: /var/lib/postgresql/data
